version: '2'
services:
  haproxy:
    image: 'dockercloud/haproxy:latest'
    links:
      - web
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mongo
  web:
    build: ../
    ports:
      - "3000"
    depends_on:
      - db
    links:
      - "db:mongo-db"